blank_issues_enabled: false
contact_links:
  - name: "â“ Questions"
    url: "https://github.com/danyaridiger/extended-click-outside/discussions"
    about: "Ask general questions in Discussions"

templates:
  - bug_report.yml
  - feature_request.yml
